<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_ConfirmPassword</name>
   <tag></tag>
   <elementGuidId>1d876ccb-0bcb-4774-8a46-8d58c9a2b109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ConfirmPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConfirmPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50358ee6-3d4c-447a-a3ed-1fc072ac07a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4d1aadb6-1c11-4bf9-844c-6234faa4a098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0fd2e1ed-7aea-4820-8e1e-bc0c889f85a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto</name>
      <type>Main</type>
      <value>The password and confirmation password do not match.</value>
      <webElementGuid>eab54879-b026-4c53-af5a-efb8e42ab461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto-other</name>
      <type>Main</type>
      <value>*.Password</value>
      <webElementGuid>acd9ad07-bd54-4978-a14e-9261b4a1e5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Password is required.</value>
      <webElementGuid>647cb837-7593-4da5-ac56-811c8e06566c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmPassword</value>
      <webElementGuid>a021d419-f411-4879-a952-999728ac2f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConfirmPassword</value>
      <webElementGuid>d8ff4dce-5f97-4f65-b212-2410d79f6f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmPassword&quot;)</value>
      <webElementGuid>04cae1ae-11c1-47c3-8d3d-c50622ddae4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConfirmPassword']</value>
      <webElementGuid>de638dec-01ea-43ff-834a-a7afc47af219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/input</value>
      <webElementGuid>9f35c560-8097-4b93-be02-f83baf5d3d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'ConfirmPassword' and @name = 'ConfirmPassword']</value>
      <webElementGuid>825cba9f-610e-475b-9c05-d5aa18be73d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
